#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for PHOTO-REPORT PostgreSQL Integration

set -e

echo "========================================"
echo "PHOTO-REPORT Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
BACKEND_PORT=8000
DB_PORT=5432

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# Check if Docker is running
check_docker() {
    if ! docker info > /dev/null 2>&1; then
        echo -e "${RED}Docker is not running. Please start Docker first.${NC}"
        exit 1
    fi
    echo -e "${GREEN}Docker is running${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================
install_dependencies() {
    echo ""
    echo -e "${BLUE}Installing Python dependencies...${NC}"

    if [ -f "requirements.txt" ]; then
        pip install -r requirements.txt
        echo -e "${GREEN}Dependencies installed${NC}"
    else
        echo -e "${RED}requirements.txt not found${NC}"
        exit 1
    fi
}

# ============================================
# CREATE DOCKER NETWORK
# ============================================
create_network() {
    echo ""
    echo -e "${BLUE}Setting up Docker network...${NC}"

    if ! docker network ls | grep -q coletor_default; then
        docker network create coletor_default
        echo -e "${GREEN}Docker network 'coletor_default' created${NC}"
    else
        echo -e "${YELLOW}Docker network 'coletor_default' already exists${NC}"
    fi
}

# ============================================
# START POSTGRESQL
# ============================================
start_postgresql() {
    echo ""
    echo -e "${BLUE}Starting PostgreSQL...${NC}"

    # Check if db service exists in docker-compose
    if docker-compose config --services 2>/dev/null | grep -q "db"; then
        docker-compose up -d db
        wait_for_service $DB_PORT "PostgreSQL"
    else
        echo -e "${YELLOW}No 'db' service in docker-compose.yml - skipping${NC}"
    fi
}

# ============================================
# RUN MIGRATIONS
# ============================================
run_migrations() {
    echo ""
    echo -e "${BLUE}Running Alembic migrations...${NC}"

    if [ -f "alembic.ini" ]; then
        alembic upgrade head
        echo -e "${GREEN}Migrations applied${NC}"
    else
        echo -e "${YELLOW}alembic.ini not found - skipping migrations${NC}"
    fi
}

# ============================================
# START BACKEND
# ============================================
start_backend() {
    echo ""
    echo -e "${BLUE}Starting FastAPI backend...${NC}"

    # Start in background
    uvicorn src.main:app --reload --host 0.0.0.0 --port $BACKEND_PORT &
    BACKEND_PID=$!
    echo "Backend PID: $BACKEND_PID"

    wait_for_service $BACKEND_PORT "Backend API"
}

# ============================================
# TEST HEALTH
# ============================================
test_health() {
    echo ""
    echo -e "${BLUE}Testing health endpoint...${NC}"

    HEALTH_RESPONSE=$(curl -s http://localhost:$BACKEND_PORT/health)
    if echo "$HEALTH_RESPONSE" | grep -q '"status":"ok"'; then
        echo -e "${GREEN}Health check passed: $HEALTH_RESPONSE${NC}"
    else
        echo -e "${RED}Health check failed: $HEALTH_RESPONSE${NC}"
    fi
}

# ============================================
# MAIN
# ============================================
main() {
    echo ""
    echo -e "${BLUE}Starting development environment...${NC}"

    # Step 1: Check Docker
    check_docker

    # Step 2: Create network
    create_network

    # Step 3: Install dependencies
    install_dependencies

    # Step 4: Start PostgreSQL
    start_postgresql

    # Step 5: Run migrations
    run_migrations

    # Step 6: Start backend
    start_backend

    # Step 7: Test health
    test_health

    # Summary
    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo "  PostgreSQL: localhost:$DB_PORT"
    echo "  Backend:    http://localhost:$BACKEND_PORT"
    echo "  API Docs:   http://localhost:$BACKEND_PORT/docs"
    echo ""
    echo "Useful commands:"
    echo "  docker-compose logs -f db                          # PostgreSQL logs"
    echo "  alembic revision --autogenerate -m 'description'   # New migration"
    echo "  pytest tests/ -v                                   # Run tests"
    echo ""
    echo "Press Ctrl+C to stop all services"

    # Wait for interrupt
    wait
}

# Run main function
main "$@"
