#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for PHOTO-REPORT

set -e

echo "========================================"
echo "Starting Development Environment"
echo "PHOTO-REPORT - Relatório Fotográfico de Obras"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# STEP 1: Create directory structure
# ============================================
echo ""
echo "Step 1: Creating directory structure..."

mkdir -p .claude/skills/photo-processor/references
mkdir -p Context
mkdir -p Tasks/Backlog Tasks/Queue Tasks/InProgress Tasks/Done
mkdir -p src/docker src/python src/frontend
mkdir -p workflows/n8n
mkdir -p scripts/sql

echo -e "${GREEN}Directory structure created${NC}"

# ============================================
# STEP 2: Create Docker network if not exists
# ============================================
echo ""
echo "Step 2: Setting up Docker network..."

if ! docker network ls | grep -q coletor_default; then
    docker network create coletor_default
    echo -e "${GREEN}Docker network 'coletor_default' created${NC}"
else
    echo -e "${YELLOW}Docker network 'coletor_default' already exists${NC}"
fi

# ============================================
# STEP 3: Build and start photo-processor container
# ============================================
echo ""
echo "Step 3: Building and starting photo-processor container..."

cd src/docker
docker-compose build
docker-compose up -d

cd ../..

wait_for_service 8002 "Photo Processor API"

# ============================================
# STEP 4: Test health endpoint
# ============================================
echo ""
echo "Step 4: Testing health endpoint..."

HEALTH_RESPONSE=$(curl -s http://localhost:8002/health)
if echo "$HEALTH_RESPONSE" | grep -q '"status":"ok"'; then
    echo -e "${GREEN}Health check passed: $HEALTH_RESPONSE${NC}"
else
    echo -e "${RED}Health check failed: $HEALTH_RESPONSE${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Photo Processor API:  http://localhost:8002"
echo "  API Docs (Swagger):   http://localhost:8002/docs"
echo "  Frontend:             file://$(pwd)/src/frontend/index.html"
echo ""
echo "Database Connection:"
echo "  Host:     host.docker.internal"
echo "  Port:     5432"
echo "  Database: cosmic"
echo "  User:     lucas"
echo ""
echo "To run SQL schema:"
echo "  docker exec -it pg psql -U lucas -d cosmic -f /scripts/sql/create-tables.sql"
echo ""
echo "To stop services:"
echo "  cd src/docker && docker-compose down"
echo ""
